project:
  type: website

website:
  title: "Trabalho Final"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    subtitle: "Estatística e Probabilidade"
    author: "Juno Takano"
    date: "2025-06-30"
    language: pt-BR
    # theme:
    #   - lux
    #   - darkly
    toc: true
    anchor-selections: true
    smooth-scroll: true



